### ISSUE TITLE
App Boilerplate: helpers

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-App#14]
Want to leave this open whilst we're building out example apps and getting the platform into a usable state.

We have the backbone-events style JSON syntax for filters, would it make sense to add this for helpers too?

I'm referring to the ability to do:

```
MyApp = App.extend({
    helpers: {
       myHelper: 'myHelper'
    },
    myHelper: function () {},
});
```

I'm not sure if the same syntax makes sense, because the name of the helper is going to be the same as the name of the function. Also, how would we distinguish between async and non-async helpers?

**Comment by k-j-kleist** [comment]
Has somebody actually created a handlebars helper using an app?

https://github.com/TryGhost/Ghost/blob/master/core/server/apps/proxy.js#L62 seems to indicate it should be possible. However this code does not work:
```
'use strict';

var App = require('ghost-app');
var MyApp;

MyApp = App.extend({

    initialize: function () {
        console.log('MyApp: initialize()');
    },

    install: function () {
        console.log('MyApp: install()');
    },

    uninstall: function () {
        console.log('MyApp: uninstall()');
    },

    activate: function () {
        console.log('MyApp: activate()');
    },

    deactivate: function () {
        console.log('MyApp: deactivate()');
        },

    // https://github.com/TryGhost/Ghost/blob/master/core/server/apps/proxy.js#L62

    // "package.json":
    //
    // "ghost": {
    //    "permissions": {
    //        "helpers": ["fb_post_url"]
    //    }
    // }

    helpers: {
        fb_post_url: 'getFbPostUrl'
    },

    getFbPostUrl: function(fb_post_url) {
            return('http://example.com/foo/bar/baz');
    }

});

module.exports = MyApp;
```
I'd hate to abuse `config.js` as often suggested by posts like this:

http://zackehh.com/safely-creating-custom-handlebars-helpers/

**Comment by ErisDS** [comment]
This issue was closed because this version of the syntax was proposed and then rejected ;)

Therefore the way to register a helper is via the app proxy object as part of the activate function:

```
activate: function () {
    console.log('MyApp: activate()');
    this.app.helpers.register('fb_post_url', this.getFbPostUrl);
}
```

Prolly worth adding that to the docs if you have a second :+1:

**Comment by k-j-kleist** [comment]
Works like a charm (using "this.ghost" instead of "this.app"), thanks!

I've updated https://github.com/TryGhost/Ghost/wiki/Apps-Getting-Started-for-Ghost-Devs accordingly.
