### ISSUE TITLE
Setting up a new ghost app.

### ISSUE THREAD

**Issue by andrew-luhring** [TryGhost/Ghost-App#19]
`first issue :-)`

So... I've been digging through the ghost source all day today trying to find a way to hook into the Posts array and only grab the main image of every post (Protip: there isn't one... As far as I can tell, anyway -- even though each post does, in fact, have an "image" property).
Anyway, at some point I stumbled onto this api feature, and now I'm here.
So hi.

How do I install an app I make?
I've read [this](https://github.com/TryGhost/Ghost/wiki/Apps-Getting-Started-for-Ghost-Devs) 
And I'm stuck on [this](https://github.com/TryGhost/Ghost/wiki/Apps-Getting-Started-for-Ghost-Devs#installing) because I am evidently so bad at sql, that I can't add an item to an array.

In 
`/content/data/blah.ghost.json`
I see:

``` json

   {
        "id": 15,
        "uuid": "a number",
        "key": "activeApps",
        "value": "[]",
        "type": "app",
        "created_at": 1408810169322,
        "created_by": 1,
        "updated_at": 1408837881785,
        "updated_by": 1
      }

```

so I:

``` json

   {    
        "id" : 15,
        "key": "activeApps",
        "value": ["appName"],
    }

```

And that didn't... blow anything to pieces, but it still doesn't work-- or if it does, I can't figure out how to make it say so...
I stopped and restarted ghost.
Nothin.
Where am I going wrong?

**Comment by k-j-kleist** [comment]
I just updated the "Installing" part of https://github.com/TryGhost/Ghost/wiki/Apps-Getting-Started-for-Ghost-Devs. Note the backslash escaped double quotes!

Seems to work for me, but as of now I've just added `console.log()` to the lifecycle methods. Next step: adding a handlebar helper (although https://github.com/TryGhost/Ghost-App/issues/14 is not very encouraging... )
