### ISSUE TITLE
Accessing config inside custom application

### ISSUE THREAD

**Issue by milosh012** [TryGhost/Ghost-App#21]
Hello,

I need to access site global config inside app. How I can do this? 

For example I need to access `server.host` variable depending on the NODE_ENV.

Thanks in advance,
Milos

**Comment by avsd** [comment]
Hi @milosh012 

Here is something that may help you: https://github.com/uploadcare/uploadcare-ghost-demo/pull/4/files#diff-bcd5149c7fd32f4f107e57b95fe4fec1R22 - search for "uploadcarePublicKey" across the code.

Is your app public or proprietary? I would like to know how are you integrating it with core of Ghost, as I am stuck with it... The app we are developing is currently available as a patch to Ghost, and I'd like to make it installable.

Can you help?

**Comment by ErisDS** [comment]
@milosh012 Ghost Apps are still very much a work in progress, and the config is not yet exposed to the app in any way. I'm afraid these apps are simply not ready for prime time yet.
