### ISSUE TITLE
App permission missing?

### ISSUE THREAD

**Issue by letsjustfixit** [TryGhost/Ghost-App#22]
Possibly unhandled Error  at Error.NoPermissionError (v:\weblapok\git\ghost.dev\Ghost.fork\core\server
\errors\no-permission-error.js:6:18)[..]
While I have all this shoved inside the app's package.json (tried to build a possible permissions page :) )..
My questoin is how to properly access the notifications api?
Regards,

"ghost": {
    "permissions": {
      "api.apps":           ["browse", "read", "edit", "add", "delete"],
      "api.authentication": ["browse", "read", "edit", "add", "destroy"],
      "api.configuration":  ["browse", "read", "edit", "add", "destroy"],
      "api.db":             ["exportContent", "importContent"],
      "api.mail":           ["browse", "read", "edit", "add", "destroy"],
      "api.notifications":   ["browse", "read", "add", "destroy", "destroyAll"],
      "notifications":   ["browse", "read", "add", "destroy", "destroyAll"],
      "api.posts":          ["browse", "read", "edit", "add", "destroy"],
      "api.routes":         ["browse", "read", "edit", "add", "destroy"],
      "api.roles":          ["browse", "read", "edit", "add", "destroy"],
      "api.slugs":          ["browse", "read", "edit", "add", "destroy"],
      "api.tags":          ["browse", "read", "edit", "add", "destroy"],
      "api.themes":          ["browse", "edit"],
      "api.uploads":          ["add"],
      "api.settings":       ["browse", "read", "edit", "add", "delete"],
      "api.users":          ["browse", "read", "edit", "add", "destroy"],
      "helpers":        ["browse", "read", "edit", "add", "destroy"],
      "filters":        ["ghost_head","ghost_foot"]  
    }
  }

**Comment by ErisDS** [comment]
@letsjustfixit hopefully after all the chats in IRC you've realised that apps are just not ready yet. Going to close this for now, we'll add proper documentation as soon as they are ready for proper use.
