### ISSUE TITLE
Update package.json to support Node v0.12 ?

### ISSUE THREAD

**Issue by k-j-kleist** [TryGhost/Ghost-App#23]
Now with Ghost working fine on Node v0.12, is there a reason for this limitation?
```
"engines": {
        "node": "0.10.*"
    }
```

**Comment by ErisDS** [comment]
The only reason is that this package hasn't been worked on for a year ;)

**Comment by ErisDS** [comment]
FYI - in other words that meant raise a PR :P

**Comment by halfdan** [comment]
The PR was merged - this can be closed I think?
