### ISSUE TITLE
Example Route App - Paypal Instant Notification

### ISSUE THREAD

**Issue by theunknownartisthour** [TryGhost/Ghost-App#26]
Trying to understand the docs, saw https://github.com/TryGhost/Ghost/issues/6584

An overview of how apps appear to work now would be awesome...of course wouldn't come empty handed, here's the cut dry code works if added into /core/server/routes/frontend.js, api is required.

Adds paypal instant notifications to the ghost backend :)
```
var api = require('../api');
...
```
Should work if apps get to add their own routes...however that's done

```javascript
        ...
	router.post('/paypal/notification/:sandbox', function(req, res){
		
		console.log('Received POST /');
		console.log(req.body);
		console.log('\n\n');
		
		// assign posted variables to local variables
		var item_name = req.body['item_name'];
		var item_number = req.body['item_number'];
		var payment_status = req.body['payment_status'];
		var payment_amount = req.body['mc_gross'];
		var payment_currency = req.body['mc_currency'];
		var txn_id = req.body['txn_id'];
		var receiver_email = req.body['receiver_email'];
		var payer_email = req.body['payer_email'];
		var payer_status = req.body['payer_status'];
		var address_status = req.body['address_status'];
		var first_name = req.body['first_name'];
		var last_name = req.body['last_name'];
		
		//var note = payer_email+' purchased '+item_name+'#'+item_number+' now '+payment_status+' for '+payment_amount+payment_currency;
		var note = payer_email+'<br>'+item_name+' #'+item_number+'<br>'+payment_status+'<br>'+payment_amount+payment_currency;
		
		var notetype = 'info';
		var status = payment_status.toUpperCase();
		
		if(status == "COMPLETED"){
			notetype = 'success';
		} 
		else if(status == "DENIED"){
			notetype = 'error';
		} 
		else if(status == "EXPIRED"){
			notetype = 'warn';
		} 
		else if(status == "FAILED"){
			notetype = 'error';
		}
		else if(status == "IN-PROGRESS"){
			notetype = 'info';
		}
		else if(status == "PARTIALLY_REFUNDED"){
			notetype = 'info';
		}
		else if(status == "PENDING"){
			notetype = 'info';
		}
		else if(status == "PROCESSED"){
			notetype = 'info';
		}
		else if(status == "REFUNDED"){
			notetype = 'warn';
		}
		else if(status == "REVERSED"){
			notetype = 'warn';
		}
		else if(status == "VOIDED"){
			notetype = 'warn';
		}
		else if(status == "CANCELED_REVERSAL"){
			notetype = 'warn';
		} else {
			notetype = 'info';
		}
		
		
		// type can be 'error', 'success', 'warn' and 'info'
		
		var notification = {
			type: notetype,
			message: note,
			location: 'top',
			dismissible: true
		};
		

		console.log("Adding note: "+note);
		
		var usernote = 'info';
		if(address_status.toUpperCase() == 'UNCONFIRMED'){
			usernote = 'warn';
		} else if(payer_status.toUpperCase() == 'UNVERIFIED'){
			usernote = 'warn';
		}
		
		api.notifications.add({notifications: [{
			type: usernote,
			message: first_name+' '+last_name+':'+payer_email+'<br>Address:'+address_status+'<br>Account:'+payer_status,
		}]}, {context: {internal: true}});
		
		api.notifications.add({notifications: [{
			type: notetype,
			message: note,
		}]}, {context: {internal: true}});

		console.log("Before send");
		
		// STEP 1: read POST data
		req.body = req.body || {};
		res.send(200, 'OK');
		res.end();

	});
```

**Comment by ErisDS** [comment]
Hi @theunknownartisthour, apps are not really a thing just yet. All of the documentation that exists is over on the [Ghost Wiki](https://github.com/TryGhost/Ghost/wiki), but it's all very much up in the air and subject to (significant) change.

The concept of apps was too broad and too abstract for us to really move forward with, which is why we've changed tactics and are building things like #6584 directly into core for now. This way we can test out useful integrations and extensions, see how people use them, and then much like with [private blogging](https://github.com/TryGhost/Ghost/issues/6589) we can start working on splitting them out and figuring out what extension points we really need rather than trying to speculatively add them in.

At the moment there is no way for an app to register a route, and at present, no plans just yet for how that will happen.There lots of possibilities developing in that area with the work on [channels](https://github.com/TryGhost/Ghost/wiki/Channels-101). And I'm sure things will evolve as we work moving on private blogging and other features into modules.

However I think the code you've posted here is a pretty great example of something that should *not* be an app! Here's why..

It's really easy to run Ghost alongside, or even integrated with other express applications. Setting up a small express app with the routes for getting incoming webhooks from paypal should be straightforward. Then, you can send the notifications to Ghost by way of the JSON API - that's what the API is for!

Seeing as there's no other integration points here - the App lifecycle doesn't fit and you're not affecting the actual behaviour of Ghost itself in any way, it really doesn't make sense to run it inside Ghost in a "Ghost App". Why couple code that doesn't need to be coupled?

**Comment by theunknownartisthour** [comment]
This was one of my straightforward customizations I've built into my own ghost frontend router, I understood it wouldn't be practical as an app just to add a single route. What I was getting to is that when/if custom routing for apps is available this would be an easy to understand integration.

Currently I'm attempting to integrate an external ecommerce api from schema.io, and channels did not solve my problem because I wasn't following along with the regular flow they'd generate errors for missing metadata (it was attempting to pull data from posts which didn't exist, I wasn't giving it a post to template). 

So I added this to controllers\frontend\index.js:
```javascript
	results: function (req, res) {
        var defaultPage = path.resolve(config.paths.adminViews, 'results.hbs');
        return getActiveThemePaths().then(function (paths) {
            var data = {};
            if (res.error) {
                data.error = res.error;
				data.errorcode = res.errorcode;
				console.log(data.error);
				return errors.renderErrorPage(data.errorcode,data.error,req,res,null);
            } else {
				data.songlist = res.songlist;
				data.queuelist = res.queuelist;
				console.log(data.songlist);
				console.log(data.queuelist);
			}
            data.renderobject = res.renderobject;
            console.log(data.renderobject);
            
            setResponseContext(req, res);
			
			if(res.renderpath){
				if (paths.hasOwnProperty(res.renderpath+'.hbs')) {
					return res.render(res.renderpath,data);
				}
			}
			
            if (paths.hasOwnProperty('results.hbs')) {
                return res.render('results', data);
            } else {
                return res.render(defaultPage, data);
            }
        });
    }
```

which allowed me to write functions I could add into the routes/frontend.js and add routes that I wanted to be templated out by ghost:
```javascript
/*I have way more routes and functions than this...*/
	router.get('/song/:songid',search);
	router.get('/artist/:artist',search);
	router.get('/title/:title',search);
	router.get('/album/:album',search);
```
(this is running queries against another SQL database (not hosting ghost))
```javascript
function search(req,res){
	/*SELECT SQL_CACHE * FROM SONGS WHERE ?*/
	var sql = "SELECT SQL_CACHE * FROM songs WHERE ";
	var sqlmid = "";
	var sqlend = " AND (play_limit = 0 OR count_played < play_limit);";
	/* AND enabled=1 AND song_type=0 */
	var cols = {
		artist: "artist",
		title: "title",
		album: "album",
		id: "songid"
	};
	
	var searchlike = {
		artist: "?? LIKE '%?%'",
		title: "?? LIKE '%?%'",
		album: "?? LIKE '%?%'",
		id: "?? = ?",
		enabled: "?? = ?",
		song_type: "?? = ?"
	}
	
	var inserts = {
		enabled: 1,
		song_type: 0
	};
	
	for(var key in cols){
		if (typeof cols[key] !== 'function') {
			if(req.params[cols[key]]){
				inserts[key] = {};
				inserts[key] = req.params[cols[key]];
				console.log(inserts[key]);
			}
		}
	}
	
	var insertcount = 0;
	for(var key in inserts){
		console.log(key);
		if(typeof inserts[key] !== 'function'){
			if(insertcount != 0){
				/*sqlmid += ' AND '+searchlike[key];*/
				sqlmid += ' AND '+searchlike[key].replace('??',key).replace('?',mysql.escape(inserts[key])).replace("'%'","'%").replace("'%'","%'");
			} else {
				sqlmid += searchlike[key].replace('??',key).replace('?',mysql.escape(inserts[key])).replace("'%'","'%").replace("'%'","%'");
				/*sqlmid += searchlike[key];*/
			}
			console.log(sqlmid);
			insertcount++;
		}
	}
	
	var sqlquery = sql+sqlmid+sqlend;
	console.log(sqlquery);
	//var sqlformatted = mysql.format(sqlquery,inserts);
	var sqlformatted = sqlquery;
	console.log(sqlformatted);
	var query = radiodj.query(sqlformatted,function(err,result){
		if(err){
			console.log(err);
		} else {
			if(req.query.json){
				res.json(result);
			} else {
				res.songlist = result;
				frontend.results(req,res);
			}
		}
	});
	/*console.log(query.sql);*/
}
```

These are the types of things I wanted to wrap up nicely in an app, so that I wouldn't need to overwrite core ghost files.

**Comment by theunknownartisthour** [comment]
This seems relatively clear cut:
https://github.com/AileenCGN/Ghost/tree/apps-slack
minus the frontend routing problem...I guess I'll work on it
https://github.com/theunknownartisthour/GhostSchema/tree/apps-schemaIO
