### ISSUE TITLE
Move 0.0.2 tag to the latest working commit (or at least one working)

### ISSUE THREAD

**Issue by tonydotgit** [TryGhost/Ghost-App#30]
Hello guys,

Trying to build a testing app here and I figured out that your Wiki doesn't match with the **0.0.2** version of Ghost-App.

The main issue is the Proxy name, in 0.0.2 tag is still called `this.app` but in the commit ac4fb8a06e985383ed74288946cfefcbf9d03ceb this was changed from `this.app` to `this.ghost` as the Wiki says but the tag (0.0.2) was not moved there.

**Reference Link:** [this.ghost is undefined](https://forum.ghost.org/t/ghost-app-this-ghost-is-undefined/2480/2)

**Comment by kirrg001** [comment]
Thanks! I have updated our wiki. Please use version 0.0.3 👍
